title: Valker's Tech Blog
email: neolunar7@gmail.com
author:
  picture: http://site.hugocarreira.me/assets/img/compressed/hugo.jpg #URL FORMAT
  name: Piljae Chae
  location: Seoul, South Kor
  description: "22 years old, studying computer science"  
description: only my simple vision of casper theme
baseurl: ""
url: "https://neolunar7.github.io"
github_username: neolunar7
github_url: https://neolunar7.github.io/

# Build settings
permalink: :title
paginate: 1
paginate_path: "page:num"
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
